language: node_js
node_js:
  - "iojs"
  - "7"
install:
  - npm install
  - pip install codecov
  - pip install coverage
env:
  - BOT_TOKEN = "X"
script:
  - coverage run ./index.coffee
after_success:
 - bash < (curl -s https://codecov.io/bash) -t 10b28681-2e7b-4fdc-b2a3-546d89e1145b
